spring:
 thymeleaf:
   cache: false
 security:
   oauth2:
     client:
       registration:
         okta:
           client-id: 0oaizo9n4KaJvQ9l6356
           client-secret: KSIFhGTLwmnSZizwLvLE93uHlIgRMnsrSpRmUASJ
       provider:
         okta:
           authorization-uri: https://dev-523262.okta.com/oauth2/default/v1/authorize
           token-uri: https://dev-523262.okta.com/oauth2/default/v1/token
           user-info-uri: https://dev-523262.okta.com/oauth2/default/v1/userinfo
           jwk-set-uri: https://dev-523262.okta.com/oauth2/default/v1/keys
